server:
  port: 5005
  runMode: debug
logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug
  logger: zap
cors:
  allowOrigins: "*"

postgres:
  host: postgres_container
  port : 5432
  user: postgres
  password: Password12!
  dbName: car_sale_db
  sslMode: disable
  maxIdleConns: 15
  maxOpenConns: 100
  connMaxLifetime: 5

redis:
  host: redis_container
  port: 6379
  password: password
  db: 0
  dialTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  poolSize: 10
  poolTimeout: 15
  idleCheckFrequency: 500

PasswordConfig:
  IncludeChars: true
  IncludeDigits: true
  MinLength: 8
  MaxLength: 20
  IncludeUppercase: true
  IncludeLowercase: true


